[config]
version_check = false

[config.wallpaper]
command = "feh"
arguments = ["--bg-fill"]
type = "SchemeVibrant"
mode = "dark"

 
[templates.kitty]
input_path = '~/dotfiles/configs/matugen/templates/kitty-colors.conf'
output_path = "~/dotfiles/configs/kitty/theme.conf"

