#!/bin/sh

# Border colors
bspc config normal_border_color "#6e6a86"
bspc config active_border_color "#9ccfd8"
bspc config focused_border_color "#9ccfd8"
bspc config presel_feedback_color "#9ccfd8"

# Save current theme name for other scripts
bsp_color="rosepine"

# You might want to export these variables for other scripts to use
export BSP_NORMAL_COLOR="#6e6a86"
export BSP_ACTIVE_COLOR="#9ccfd8"
export BSP_FOCUSED_COLOR="#9ccfd8"
export BSP_PRESEL_COLOR="#9ccfd8"
