swipe:
  2:
    left:
      command: 'xdotool key alt+Right'  # Forward
    right:
      command: 'xdotool key alt+Left'   # Back
  3:
    left:
      command: 'hyprctl dispatch workspace e+1'
    right:
      command: 'hyprctl dispatch workspace e-1'
    up:
      command: 'rofi -show drun'
    down:
      command: 'rofi -show drun'

threshold:
  swipe: 0.3

interval:
  swipe: 0.8
