#!/usr/bin/env bash

autostart() {
	if ! pgrep -fx "$1" ; then
		"$@"&
	fi
}

# autostart
# usage: autostart [command]

xrandr --output eDP-1 --off --output DP-1-2 --primary --mode 3440x1440 --pos 0x0 --rotate normal 

eval "$(ssh-agent -s)"

autostart xsettingsd

autostart "$HOME"/.fehbg

autostart "$HOME"/.config/polybar/launch.sh

autostart dunst

autostart picom

autostart xfce4-power-manager

#autostart /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

autostart unclutter

autostart udiskie
