# ~/.config/hypr/hyprlock.conf

general {
    # background image
    background = path:/home/abe/Pictures/Wallpapers/lock.jpg
    no_fade_in = false
    grace = 0
}

input-field {
    monitor = eDP-1  # Or use "*" for all
    size = 200, 50
    outline_thickness = 3
    outer_color = rgba(000000aa)
    inner_color = rgba(1e1e2e88)
    font_color = rgba(ffffffee)
    placeholder_text = <password>
    placeholder_color = rgba(888888cc)
    dots_center = true
    fade_on_empty = false
    invert_on_fail = true
}

label {
    text = Welcome back, Abe
    color = rgba(ffffffdd)
    font_size = 24
    position = 0, 180
    font_family = JetBrainsMono Nerd Font
}
