# ~/.config/hypr/hyprland.conf

exec-once = hyprpm reload -n

source = ~/.config/hypr/keybinds.conf

monitor=DP-3,3440x1440@100,0x0,1
monitor=HDMI-A-1,3440x1440@100,0x1440,1

exec-once = source ~/.config/hypr/autostart.sh

misc {
  allow_session_lock_restore = true
}

gestures {
workspace_swipe = on
workspace_swipe_distance = 2
workspace_swipe_create_new = false
workspace_swipe_forever = false
}

plugin {
  split-monitor-workspaces {
    count = 5                       # 1–5 per monitor
    keep_focused = 1                # preserve focused WS on reload
    enable_notifications = 0
    enable_persistent_workspaces = 1
    enable_wrapping = 1
  }
}

input {
    kb_layout = us,se
    kb_variant =
    kb_options = grp:alt_shift_toggle 
    follow_mouse = 1
    # natural_scroll = no # Keep this 'no' if you don't want it globally for *all* input devices
    sensitivity = 0.4   # Keep this at default if you don't want it globally for *all* input devices

    touchpad {
        disable_while_typing = true
        clickfinger_behavior = true
        tap-to-click = true
        scroll_factor = 0.8
        natural_scroll = yes # APPLY NATURAL SCROLL TO ALL TOUCHPADS
    }

    device {
        #magic-trackpad-2-mouse {
        apple-inc.-magic-trackpad {
        }
    }
}

decoration {
    rounding = 8

    blur {
        enabled = yes
        size = 5
        passes = 2
        new_optimizations = yes
        noise = 0.0117
        contrast = 0.8916
        brightness = 0.8172
    }

    shadow {
        enabled = yes
        range = 15
        render_power = 3
        color = rgba(1a1a1aee)
    }

    active_opacity = 1.0
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0
}

animations {
    enabled = yes
    bezier = ease, 0.25, 0.1, 0.25, 1
    animation = windows, 1, 5, ease
    animation = fade, 1, 5, ease
}

bind = ,swipe:3:l,workspace,e+1
bind = ,swipe:3:r,workspace,e-1
bind = ,swipe:3:u,exec,hyprctl dispatch togglespecialworkspace
bind = ,swipe:3:d,exec,hyprctl dispatch togglespecialworkspace

bind = ,swipe:4:u,exec,~/.config/hypr/scripts/app_overview.sh
bind = ,swipe:4:d,exec,hyprctl dispatch killactive
bind = ,swipe:4:l,movefocus,l
bind = ,swipe:4:r,movefocus,r
