# Terminal
bind = SUPER,Return,exec,kitty
bind = SUPER SHIFT,Return,exec,kitty --name float --class float

# App launcher
bind = SUPER,space,exec,wofi --show drun

# Power menu
#bind = SUPER,Backspace,exec,sh ~/dotfiles/configs/colors/color
bind = SUPER, BACKSPACE, exec, ~/.config/hypr/scripts/wofi-theme-picker.sh
# Lock screen
bind = SUPER,l,exec,hyprlock

# Reload Hyprland
bind = SUPER ALT,r,exec,hyprctl reload

# Language toggle
#bind = SUPER ALT,l,exec,sh ~/dotfiles/configs/hypr/scripts/toggle-keyboard.sh
bind = SUPER ALT, l, exec, hyprctl switchxkblayout rama-works-rama-works-m60-a next
# Quit Hyprland
bind = SUPER ALT,q,exit,

# Close/kill window
bind = SUPER,x,killactive,
bind = SUPER SHIFT,x,exec,hyprctl killactive

# --- Mouse Bindings ---
bindm = SUPER,mouse:272,movewindow
bindm = SUPER,mouse:273,resizewindow

# Fullscreen / floating
bind = SUPER,t,togglefloating,
bind = SUPER,s,fullscreen,

# Move focus
bind = SUPER,h,movefocus,l
bind = SUPER,j,movefocus,d
bind = SUPER,k,movefocus,u
bind = SUPER,l,movefocus,r

# Swap windows
bind = SUPER SHIFT,h,swapwindow,l
bind = SUPER SHIFT,j,swapwindow,d
bind = SUPER SHIFT,k,swapwindow,u
bind = SUPER SHIFT,l,swapwindow,r

# --- Workspace switching (with split-monitor-workspaces) ---
bind = SUPER,1,split-workspace,1
bind = SUPER,2,split-workspace,2
bind = SUPER,3,split-workspace,3
bind = SUPER,4,split-workspace,4
bind = SUPER,5,split-workspace,5

bind = SUPER SHIFT, 1, split-movetoworkspacesilent, 1
bind = SUPER SHIFT, 2, split-movetoworkspacesilent, 2
bind = SUPER SHIFT, 3, split-movetoworkspacesilent, 3
bind = SUPER SHIFT, 4, split-movetoworkspacesilent, 4
bind = SUPER SHIFT, 5, split-movetoworkspacesilent, 5

# Focus between monitors
bind = SUPER,Tab,exec,split-monitor-workspaces focus right
bind = SUPER SHIFT,Tab,exec,split-monitor-workspaces focus left

