# ~/.config/hypr/trackpad.conf

# Match: apple-inc.-magic-trackpad
device:apple-inc.-magic-trackpad {
  natural_scroll = yes
  scroll_factor = 0.9
  sensitivity = 0              # pointer accel neutral
  accel_profile = adaptive
  tap-and-drag = true
  middle_button_emulation = true
}

# Some kernels/BT stacks create a second logical device
# Match: apple-inc.-magic-trackpad-1
device:apple-inc.-magic-trackpad-1 {
  natural_scroll = yes
  scroll_factor = 0.9
  sensitivity = 0
  accel_profile = adaptive
  tap-and-drag = true
  middle_button_emulation = true
}

