#! /bin/sh

## sxhkd start
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
bspc monitor -d 1 2 3 4 5

 
#BSPWM configuration
bspc config border_width         2
bspc config window_gap           15
bspc config split_ratio          0.50
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

$HOME/dotfiles/bspwm/theme.conf &
#BSPWM coloring
#bspc config normal_border_color		"#d3c6aa"
#bspc config active_border_color		"#d3c6aa"
#bspc config focused_border_color	"#a7c080"
bspc config presel_feedback_color	"#ff9e64"
bspc config urgent_border_color 	"#dd2727"

bspc rule -a yubioath-desktop \
  state=floating sticky=on follow=off focus=on

# Autostart

$HOME/dotfiles/polybar/blocks/launch.sh &
picom --config $HOME/dotfiles/picom/picom.conf --experimental-backends &
setxkbmap -option grp:alt_shift_toggle us,se &
#feh --bg-fill $theme.jpg 
dunst &

