#! /bin/sh

# Source configuration
source $HOME/.config/bspwm/config

## sxhkd start
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

# Display settings
xset s off &
xset -dpms &
xset s noblank &

# Monitor setup
xrandr --output DP-4 --primary --mode 3440x1440 --rate 100 --pos 3850x1440 \
       --output DP-2 --mode 3440x1440 --rate 100 --pos 3850x0 \
       --output DP-0 --mode 3840x2160 --rate 60 --pos 0x720

bspc monitor DP-4 -d DP-4_1 DP-4_2 DP-4_3 DP-4_4 DP-4_5
bspc monitor DP-2 -d DP-2_1 DP-2_2 DP-2_3 DP-2_4 DP-2_5

bsp_remove_unplugged_monitors=false
bsp_remove_disabled_monitors=false

#BSPWM configuration
bspc config border_width         3
bspc config window_gap           20
bspc config split_ratio          0.5
bspc config top_padding          20 
bspc config bottom_padding       0 
bspc config left_padding         0 
bspc config right_padding        0 
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# Window rules
bspc rule -a feh state=floating
bspc rule -a float:float state=floating center=true rectangle=800x600+0+0

# Colors
bspc config normal_border_color "$normal_border_color"
bspc config focused_border_color "$focused_border_color"

# Fix Java Applications
export _JAVA_AWT_WM_NONREPARENTING=1

#BSPWM coloring
#bspc config normal_border_color		"#d3c6aa"
#bspc config active_border_color		"#d3c6aa"
#bspc config focused_border_color	"#a7c080"
bspc config presel_feedback_color	"#ff9e64"
bspc config urgent_border_color 	"#dd2727"

# Keyboard layout
setxkbmap us 

# Autostart
xsettingsd &
dunst &
picom &
unclutter &
udiskie &
#$HOME/lib/scripts/wm/bspwm/startup-terminals
nm-applet &

# User interface
$HOME/.fehbg &
$HOME/dotfiles/configs/polybar/launch.sh &
#$HOME/lib/scripts/wm/bspwm/startup-terminals
