foreground                      #d3c6aa
background                      #2f383e
selection_foreground            #9da9a0
selection_background            #573e4c

cursor                   #d3c6aa
cursor_text_color        #374247

active_border_color      #a7c080
inactive_border_color    #596763

# black
color0   #374247
color8   #404c51

# red
color1   #e67e80
color9   #e67e80

# green
color2   #a7c080
color10  #a7c080

# yellow
color3   #dbbc7f
color11  #dbbc7f

# blue
color4   #7fbbb3
color12  #7fbbb3

# magenta
color5   #d699b6
color13  #d699b6

# cyan
color6   #83c092
color14  #83c092

# white
color7   #859289
color15  #859289

