#! /bin/sh

processes=("sxhkd" "polybar" "dunst")
for process in "${processes[@]}"; do 
    if pgrep -x "$process" > /dev/null; then
        killall -q "$process"
    fi
done

#pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 11
bspc config top_padding -9

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true


sxhkd -c "$HOME/dotfiles/sxhkd/sxhkdrc"

# Init
"$HOME/dotfiles/bspwm/config/init" &

# Set floating windows
#bspc rule -a Thunar state = floating
#bspc rule -a kitty state = floating

# Set all floating
#bspc rule -a '*' state=floating
# Make some exceptions
bspc rule -a firefox state=tiled

# Carry zathura to top!
bspc rule -a Zathura layer = above

# Center windows
center = true

# Focus on hover
bspc config focus_follows_pointer true


# Keyboardeyboard toggle
setxkbmap -option grp:alt_shift_toggle us,se
setxkbmap -option caps:escape_shifted_capslock

# AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
NetworkManager &
dunst &
~/.config/polybar/launch.sh &

